### PR TITLE
GUI: Fix double free of children widgets in control register widget

### PR DESCRIPTION
**Pull request by JakubVanek**
Fixes https://github.com/cvut/qtrvsim/issues/76

This way, the Qt parent-child relationship is preserved. I don't know Qt well and this felt like the safer solution.

### CODE REVIEW

**Comment by JakubVanek** [comment]
I have now realized that this fix might be incomplete or wrong - it seems that the `QLabel`s inside CsrDock are managed the same way, yet the do not cause the crash.

**Comment by jdupak** [comment]
Right, static table also takes ownership and frees the label at `src/gui/statictable.cpp:32`

**Comment by jdupak** [comment]
> I have now realized that this fix might be incomplete or wrong - it seems that the `QLabel`s inside CsrDock are managed the same way, yet they do not cause the crash.

Your changes are right. And the same should be also done for the labels. Double free "randomly" corrupts memory so there is no telling, whether it will cause a crash or not.

**Comment by jdupak** [comment]
LGTM, thank you. I will merge it as soon as the CI checks finish.

**Comment by JakubVanek** [comment]
Thanks!

**Pull request merged**
