### PR TITLE
CLI: reporter dump to json

### LINKED ISSUE #99: CLI JSON output

### PR DESCRIPTION
**Pull request by trdthg**
trying to close #99 

- New cli option: `--dump-to-json <FNAME>`
- New enum: 
	```cpp
	enum DumpFormat {
	    CONSOLE = 1 << 0,
	    JSON = 1 << 1,
	};
	```
- New public member(Reporter): 
	```cpp
	public:
	    DumpFormat dump_format = DumpFormat::CONSOLE; // which format dump
	    QString dump_file_json;                       // where to dump
	    QJsonObject dump_data_json = {};              // keep data

	```
- Output example:
	```json
	{
	    "caches": {
	        "d-cache": {
	            "hit": "0",
	            "hit_rate": "0.000",
	            "improved_speed": "100.000",
	            "miss": "0",
	            "reads": "2",
	            "stalled_cycles": "36"
	        },
	        "i-cache": {
	            "hit": "0",
	            "hit_rate": "0.000",
	            "improved_speed": "100.000",
	            "miss": "0",
	            "reads": "9",
	            "stalled_cycles": "81"
	        }
	    },
	    "cycles": {
	        "cycles": "9",
	        "stalls": "0"
	    },
	    "regs": {
	        "PC": "0x00000004",
	        "R0": "0x00000000",
	        "R1": "0x00000000",
	        "R10": "0x00000000",
	        "R11": "0x00000000",
	        "R12": "0x00000000",
	        "R13": "0x00000000",
	        "R14": "0x00000000",
	        "R15": "0x00000000",
	        "R16": "0x00000000",
	        "R17": "0x00000000",
	        "R18": "0x00000000",
	        "R19": "0x00000000",
	        "R2": "0x00000000",
	        "R20": "0x00000000",
	        "R21": "0x00000000",
	        "R22": "0x00000000",
	        "R23": "0x00000000",
	        "R24": "0x00000000",
	        "R25": "0x00000000",
	        "R26": "0x00000000",
	        "R27": "0x00000000",
	        "R28": "0x00000000",
	        "R29": "0x00000000",
	        "R3": "0x00000000",
	        "R30": "0x00000000",
	        "R31": "0x00000000",
	        "R4": "0x0000bf24",
	        "R5": "0x00005678",
	        "R6": "0x000068ac",
	        "R7": "0x00000000",
	        "R8": "0x00000000",
	        "R9": "0x00000000",
	        "cycle": "0x00000009",
	        "marchid": "0x00000000",
	        "mcause": "0x00000000",
	        "mcycle": "0x00000009",
	        "mepc": "0x00000000",
	        "mhardid": "0x00000000",
	        "mie": "0x00000000",
	        "mimpid": "0x00000000",
	        "minstret": "0x00000008",
	        "mip": "0x00000000",
	        "misa": "0x40001111",
	        "mscratch": "0x00000000",
	        "mstatus": "0x00000000",
	        "mtinst": "0x00000000",
	        "mtval": "0x00000000",
	        "mtval2": "0x00000000",
	        "mtvec": "0x00000000",
	        "mvendorid": "0x00000000"
	    }
	}
	```

### CODE REVIEW

**Comment by kubakubakuba** [comment]
Hello,
I tried it out and it works nicely! Much better than manually parsing the values by regex etc.
It will most probably get merged in the near future. Thanks!

**Comment by trdthg** [comment]
Thank you very much for your feedback. :D

**Comment by jdupak** [comment]
Thank you @trdthg it looks very good and thanks to @kubakubakuba for review. I will merge git as soon as the CI passes.

**Comment by trdthg** [comment]
@jdupak fixed

**Comment by jdupak** [comment]
@trdthg Thanks for the great work. Merged.

**Pull request merged**
